__common: &common
  language: rust
  rust: stable
  cache: cargo

sudo: required
os:
  - linux
  - osx

matrix:
  include:
  - <<: *common
    os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env: COMPILER=g++-6
    script:
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; scripts/travis_ci_linux_build.sh ; fi
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; scripts/travis_ci_mac.sh ; fi
