language: rust
rust: stable
cache: cargo

os:
  - linux
  - osx

env:
    - COMPILER=g++-6
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-6

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install qt5 &&
      export QT5="`brew --prefix qt5`";
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt571-trusty --yes;
      sudo apt-get update;
      sudo apt-get install qt57base mesa-common-dev;
      sudo apt-get install -y libasound2-dev alsa-utils alsa-oss;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90;
      git clone --recursive https://github.com/deplinenoise/tundra.git;
      cd tundra;
      make;
      sudo make install;
      cd ..;
      g++ --version;
      export QT5=/opt/qt57;
   fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tundra2 linux-gcc-debug ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/mac_build_debug.sh ; fi
