__common: &common
  language: rust
  rust: stable
  cache: cargo

os:
  - linux

matrix:
  include:
  - <<: *common
    os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env: COMPILER=g++-6
    script:
        - sudo add-apt-repository ppa:beineri/opt-qt571-trusty --yes
        - sudo apt-get update
        - sudo apt-get install qt57base mesa-common-dev
        - sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
        - git clone --recursive https://github.com/deplinenoise/tundra.git
        - cd tundra
        - make
        - sudo make install
        - cd ..
        - export QT5=/opt/qt57; g++ --version ; tundra2 -v linux-gcc-debug

