version: '{build}'
skip_tags: true
environment:
  matrix:
  - GENERATOR: Visual Studio 12 Win64
    DEPS_PATH: deps64
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-msvc.exe"
  - rust-beta-x86_64-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set QT5=C:\Qt\5.7\msvc2015_64
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - git submodule update --init --recursive
build_script:
- SET BUILD_DATE_ID=%DATE% %TIME%
- SET BUILD_FILE_ID=%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%_%TIME:~0,2%%TIME:~3,2%
- echo %BUILD_FILE_ID%
- scripts\vcvarsx86_amd64.bat
- scripts\win64_build_release.cmd
- scripts\win64_release_deploy.cmd

artifacts:
  - path: hippoplayer_win_%BUILD_FILE_ID%.7z
    name: HippoPlayer

deploy:
  provider: S3
  access_key_id: AKIAIQVVO323274QSFLA
  secret_access_key: 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
  bucket: hippoplayer
  region: eu-west-3
  unzip: false
  set_public: true
  folder: master-branch-builds
  artifact: hippoplayer_win_%BUILD_FILE_ID%.7z
  on:
    branch: master
