image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
 - set QT5_LIB=C:\Qt\5.12.4\msvc2017_64\lib
 - set QT5_BIN=C:\Qt\5.12.4\msvc2017_64\bin
 - set QT5_INC=C:\Qt\5.12.4\msvc2017_64\include
 - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
 - git submodule update --init --recursive
build_script:
- SET BUILD_DATE_ID=%DATE% %TIME%
- SET BUILD_FILE_ID=%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%_%TIME:~0,2%%TIME:~3,2%
- echo %BUILD_FILE_ID%
- scripts\vcvarsx86_amd64.bat
- scripts\win64_build_release.cmd
- scripts\win64_release_deploy.cmd

artifacts:
  - path: hippoplayer_win_%BUILD_FILE_ID%.7z
    name: HippoPlayer

deploy:
  provider: S3
  access_key_id:
    secure: R0OGuV5tmE76btdKC9y4XdmHaKy59p3Ea0T1sMAjSPw=
  secret_access_key: 
    secure: vbPLnhEyRv81ki5MSXFHmK4I0CpbWsbTrpaoXY/n4cJpBKAhmE2C4NxyGDIel/QJ
  bucket: hippoplayer
  region: eu-west-3
  unzip: false
  set_public: true
  folder: master-branch-builds
  artifact: hippoplayer_win_%BUILD_FILE_ID%.7z
  on:
    branch: master
