/* automatically generated by rust-bindgen */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 31;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __LONG_DOUBLE_USES_FLOAT128: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const __TIMESIZE: u32 = 64;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const HIPPO_FILE_API_VERSION: u32 = 1;
pub const HippoMetadata_TitleTag: &'static [u8; 6usize] = b"title\0";
pub const HippoMetadata_SongTypeTag: &'static [u8; 10usize] = b"song_type\0";
pub const HippoMetadata_AuthoringToolTag: &'static [u8; 15usize] = b"authoring_tool\0";
pub const HippoMetadata_ArtistTag: &'static [u8; 7usize] = b"artist\0";
pub const HippoMetadata_AlbumTag: &'static [u8; 6usize] = b"album\0";
pub const HippoMetadata_DateTag: &'static [u8; 5usize] = b"date\0";
pub const HippoMetadata_GenreTag: &'static [u8; 6usize] = b"genre\0";
pub const HippoMetadata_MessageTag: &'static [u8; 8usize] = b"message\0";
pub const HippoMetadata_LengthTag: &'static [u8; 7usize] = b"length\0";
pub const HippoMetadata_SamplesTag: &'static [u8; 8usize] = b"sample_\0";
pub const HippoMetadata_InstrumentsTag: &'static [u8; 12usize] = b"instrument_\0";
pub const HIPPO_METADATA_API_VERSION: u32 = 1;
pub const HIPPO_SETTINGS_API_VERSION: u32 = 1;
pub const HIPPO_PLAYBACK_PLUGIN_API_VERSION: u32 = 1;
pub const HIPPO_MESSAGE_API_VERSION: u32 = 1;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub const HippoProbeResult_HippoProbeResult_Supported: HippoProbeResult = 0;
pub const HippoProbeResult_HippoProbeResult_Unsupported: HippoProbeResult = 1;
pub const HippoProbeResult_HippoProbeResult_Unsure: HippoProbeResult = 2;
#[doc = ""]
pub type HippoProbeResult = u32;
pub const HippoFileSeek_HippoFileSeek_Start: HippoFileSeek = 0;
pub const HippoFileSeek_HippoFileSeek_Current: HippoFileSeek = 1;
pub const HippoFileSeek_HippoFileSeek_End: HippoFileSeek = 2;
pub type HippoFileSeek = u32;
pub type HippoIoHandle = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoIoResult {
    pub error_message: *const ::std::os::raw::c_char,
    pub status: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoApiPrivData {
    _unused: [u8; 0],
}
pub type HippoIoErrorCode = i32;
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoIoAPI {
    pub exists: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoApiPrivData,
            filename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub read_file_to_memory: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoApiPrivData,
            filename: *const ::std::os::raw::c_char,
            dest: *mut *mut ::std::os::raw::c_void,
            size: *mut u64,
        ) -> HippoIoErrorCode,
    >,
    pub free_file_to_memory: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoApiPrivData,
            dest: *mut ::std::os::raw::c_void,
        ) -> HippoIoErrorCode,
    >,
    pub open: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoApiPrivData,
            target: *const ::std::os::raw::c_char,
            handle: *mut HippoIoHandle,
        ) -> HippoIoErrorCode,
    >,
    pub close:
        ::std::option::Option<unsafe extern "C" fn(handle: HippoIoHandle) -> HippoIoErrorCode>,
    pub size: ::std::option::Option<
        unsafe extern "C" fn(handle: HippoIoHandle, res: *mut u64) -> HippoIoErrorCode,
    >,
    pub read: ::std::option::Option<
        unsafe extern "C" fn(
            handle: HippoIoHandle,
            dest: *mut ::std::os::raw::c_void,
            size: u64,
        ) -> HippoIoErrorCode,
    >,
    pub seek: ::std::option::Option<
        unsafe extern "C" fn(
            handle: HippoIoHandle,
            type_: HippoFileSeek,
            step: i64,
        ) -> HippoIoErrorCode,
    >,
    pub priv_data: *mut HippoApiPrivData,
}
#[doc = ""]
pub type HippoFileAPI = HippoIoAPI;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoMetadataAPIPrivData {
    _unused: [u8; 0],
}
pub const HippoMetaEncoding_HippoMetaEncoding_UTF8: HippoMetaEncoding = 0;
pub const HippoMetaEncoding_HippoMetaEncoding_ShiftJS2: HippoMetaEncoding = 1;
pub type HippoMetaEncoding = u32;
pub const HippoMetadataResult_HippoMetadataResult_KeyNotFound: HippoMetadataResult = 0;
pub const HippoMetadataResult_HippoMetadataResult_UnableToMakeQuery: HippoMetadataResult = -1;
pub type HippoMetadataResult = i32;
pub type HippoMetadataId = u64;
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoMetadataAPI {
    pub priv_data: *const HippoMetadataAPIPrivData,
    pub create_url: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoMetadataAPIPrivData,
            url: *const ::std::os::raw::c_char,
        ) -> HippoMetadataId,
    >,
    pub set_tag: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoMetadataAPIPrivData,
            id: HippoMetadataId,
            tag: *const ::std::os::raw::c_char,
            data: *const ::std::os::raw::c_char,
        ),
    >,
    pub set_tag_f64: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoMetadataAPIPrivData,
            id: HippoMetadataId,
            tag: *const ::std::os::raw::c_char,
            d: f64,
        ),
    >,
    pub add_sub_song: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoMetadataAPIPrivData,
            parent_id: HippoMetadataId,
            name: *const ::std::os::raw::c_char,
            length: f32,
        ),
    >,
    pub add_sample: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoMetadataAPIPrivData,
            parent_id: HippoMetadataId,
            text: *const ::std::os::raw::c_char,
        ),
    >,
    pub add_instrument: ::std::option::Option<
        unsafe extern "C" fn(
            priv_data: *mut HippoMetadataAPIPrivData,
            parent_id: HippoMetadataId,
            text: *const ::std::os::raw::c_char,
        ),
    >,
}
pub const HippoSettingResult_HippoSettingsResult_Ok: HippoSettingResult = 0;
pub const HippoSettingResult_HippoSettingsResult_SettingNotFound: HippoSettingResult = 1;
pub const HippoSettingResult_HippoSettingsResult_KeyNotFound: HippoSettingResult = 2;
pub const HippoSettingResult_HippoSettingsResult_InvalidType: HippoSettingResult = 3;
#[doc = ""]
pub type HippoSettingResult = u32;
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoSettingsAPI {
    pub priv_data: *mut HippoSettingsAPI,
    pub get_int: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut HippoMessageAPI,
            user_data: *mut ::std::os::raw::c_void,
            setting: *const ::std::os::raw::c_char,
            key: *const ::std::os::raw::c_char,
            res: *mut ::std::os::raw::c_int,
        ) -> HippoSettingResult,
    >,
    pub get_float: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut HippoMessageAPI,
            user_data: *mut ::std::os::raw::c_void,
            setting: *const ::std::os::raw::c_char,
            key: *const ::std::os::raw::c_char,
            res: *mut f32,
        ) -> HippoSettingResult,
    >,
}
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoMessageAPI {
    pub priv_data: *mut HippoMessageAPI,
    pub send: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut HippoMessageAPI,
            data: *const ::std::os::raw::c_uchar,
            len: ::std::os::raw::c_int,
        ),
    >,
}
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoServicePrivData {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoServiceAPI {
    pub get_io_api: ::std::option::Option<
        unsafe extern "C" fn(
            private_data: *mut HippoServicePrivData,
            api_version: ::std::os::raw::c_int,
        ) -> *const HippoFileAPI,
    >,
    pub get_metadata_api: ::std::option::Option<
        unsafe extern "C" fn(
            private_data: *mut HippoServicePrivData,
            api_version: ::std::os::raw::c_int,
        ) -> *const HippoMetadataAPI,
    >,
    pub get_message_api: ::std::option::Option<
        unsafe extern "C" fn(
            private_data: *mut HippoServicePrivData,
            api_version: ::std::os::raw::c_int,
        ) -> *const HippoMessageAPI,
    >,
    pub private_data: *mut HippoServicePrivData,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoSaveAPI {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoLoadAPI {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HippoPlaybackPlugin {
    pub api_version: u64,
    pub name: *const ::std::os::raw::c_char,
    pub version: *const ::std::os::raw::c_char,
    pub probe_can_play: ::std::option::Option<
        unsafe extern "C" fn(
            data: *const u8,
            data_size: u32,
            filename: *const ::std::os::raw::c_char,
            total_size: u64,
        ) -> HippoProbeResult,
    >,
    pub supported_extensions:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub create: ::std::option::Option<
        unsafe extern "C" fn(services: *const HippoServiceAPI) -> *mut ::std::os::raw::c_void,
    >,
    pub destroy: ::std::option::Option<
        unsafe extern "C" fn(user_data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub event: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            data: *const ::std::os::raw::c_uchar,
            len: ::std::os::raw::c_int,
        ),
    >,
    pub open: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            buffer: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub close: ::std::option::Option<
        unsafe extern "C" fn(user_data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub read_data: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            dest: *mut ::std::os::raw::c_void,
            max_sample_count: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub seek: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            ms: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub metadata: ::std::option::Option<
        unsafe extern "C" fn(
            url: *const ::std::os::raw::c_char,
            services: *const HippoServiceAPI,
        ) -> ::std::os::raw::c_int,
    >,
    pub save: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            save_api: *const HippoSaveAPI,
        ) -> ::std::os::raw::c_int,
    >,
    pub load: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            load_api: *const HippoLoadAPI,
        ) -> ::std::os::raw::c_int,
    >,
}
