[package]
name = "hippo_api"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]

[dependencies]
rute = { path = "../../../external/rute" }
rmp-serde = "0.13.7"
serde = "1.0"
serde_derive = "1.0"

