// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(non_camel_case_types)]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum MessageType {
  NONE = 0,
  next_song = 1,
  prev_song = 2,
  play_song = 3,
  stop_song = 4,
  select_song = 5,
  request_add_urls = 6,
  reply_added_urls = 7,

}

const ENUM_MIN_MESSAGE_TYPE: u8 = 0;
const ENUM_MAX_MESSAGE_TYPE: u8 = 7;

impl<'a> flatbuffers::Follow<'a> for MessageType {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for MessageType {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = u8::to_le(self as u8);
    let p = &n as *const u8 as *const MessageType;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = u8::from_le(self as u8);
    let p = &n as *const u8 as *const MessageType;
    unsafe { *p }
  }
}

impl flatbuffers::Push for MessageType {
    type Output = MessageType;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<MessageType>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
const ENUM_VALUES_MESSAGE_TYPE:[MessageType; 8] = [
  MessageType::NONE,
  MessageType::next_song,
  MessageType::prev_song,
  MessageType::play_song,
  MessageType::stop_song,
  MessageType::select_song,
  MessageType::request_add_urls,
  MessageType::reply_added_urls
];

#[allow(non_camel_case_types)]
const ENUM_NAMES_MESSAGE_TYPE:[&'static str; 8] = [
    "NONE",
    "next_song",
    "prev_song",
    "play_song",
    "stop_song",
    "select_song",
    "request_add_urls",
    "reply_added_urls"
];

pub fn enum_name_message_type(e: MessageType) -> &'static str {
  let index = e as u8;
  ENUM_NAMES_MESSAGE_TYPE[index as usize]
}

pub struct MessageTypeUnionTableOffset {}
pub enum HippoNextSongOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoNextSong<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoNextSong<'a> {
    type Inner = HippoNextSong<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoNextSong<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoNextSong {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        _args: &'args HippoNextSongArgs) -> flatbuffers::WIPOffset<HippoNextSong<'bldr>> {
      let mut builder = HippoNextSongBuilder::new(_fbb);
      builder.finish()
    }

}

pub struct HippoNextSongArgs {
}
impl<'a> Default for HippoNextSongArgs {
    #[inline]
    fn default() -> Self {
        HippoNextSongArgs {
        }
    }
}
pub struct HippoNextSongBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoNextSongBuilder<'a, 'b> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoNextSongBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoNextSongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoNextSong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoPrevSongOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoPrevSong<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoPrevSong<'a> {
    type Inner = HippoPrevSong<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoPrevSong<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoPrevSong {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        _args: &'args HippoPrevSongArgs) -> flatbuffers::WIPOffset<HippoPrevSong<'bldr>> {
      let mut builder = HippoPrevSongBuilder::new(_fbb);
      builder.finish()
    }

}

pub struct HippoPrevSongArgs {
}
impl<'a> Default for HippoPrevSongArgs {
    #[inline]
    fn default() -> Self {
        HippoPrevSongArgs {
        }
    }
}
pub struct HippoPrevSongBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoPrevSongBuilder<'a, 'b> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoPrevSongBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoPrevSongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoPrevSong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoPlaySongOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoPlaySong<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoPlaySong<'a> {
    type Inner = HippoPlaySong<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoPlaySong<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoPlaySong {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        _args: &'args HippoPlaySongArgs) -> flatbuffers::WIPOffset<HippoPlaySong<'bldr>> {
      let mut builder = HippoPlaySongBuilder::new(_fbb);
      builder.finish()
    }

}

pub struct HippoPlaySongArgs {
}
impl<'a> Default for HippoPlaySongArgs {
    #[inline]
    fn default() -> Self {
        HippoPlaySongArgs {
        }
    }
}
pub struct HippoPlaySongBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoPlaySongBuilder<'a, 'b> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoPlaySongBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoPlaySongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoPlaySong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoStopSongOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoStopSong<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoStopSong<'a> {
    type Inner = HippoStopSong<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoStopSong<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoStopSong {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        _args: &'args HippoStopSongArgs) -> flatbuffers::WIPOffset<HippoStopSong<'bldr>> {
      let mut builder = HippoStopSongBuilder::new(_fbb);
      builder.finish()
    }

}

pub struct HippoStopSongArgs {
}
impl<'a> Default for HippoStopSongArgs {
    #[inline]
    fn default() -> Self {
        HippoStopSongArgs {
        }
    }
}
pub struct HippoStopSongBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoStopSongBuilder<'a, 'b> {
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoStopSongBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoStopSongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoStopSong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoSelectSongOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoSelectSong<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoSelectSong<'a> {
    type Inner = HippoSelectSong<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoSelectSong<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoSelectSong {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args HippoSelectSongArgs<'args>) -> flatbuffers::WIPOffset<HippoSelectSong<'bldr>> {
      let mut builder = HippoSelectSongBuilder::new(_fbb);
      if let Some(x) = args.name { builder.add_name(x); }
      builder.finish()
    }

    pub const VT_NAME: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(HippoSelectSong::VT_NAME, None)
  }
}

pub struct HippoSelectSongArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for HippoSelectSongArgs<'a> {
    #[inline]
    fn default() -> Self {
        HippoSelectSongArgs {
            name: None,
        }
    }
}
pub struct HippoSelectSongBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoSelectSongBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoSelectSong::VT_NAME, name);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoSelectSongBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoSelectSongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoSelectSong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoRequestAddUrlsOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoRequestAddUrls<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoRequestAddUrls<'a> {
    type Inner = HippoRequestAddUrls<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoRequestAddUrls<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoRequestAddUrls {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args HippoRequestAddUrlsArgs<'args>) -> flatbuffers::WIPOffset<HippoRequestAddUrls<'bldr>> {
      let mut builder = HippoRequestAddUrlsBuilder::new(_fbb);
      if let Some(x) = args.urls { builder.add_urls(x); }
      builder.finish()
    }

    pub const VT_URLS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn urls(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<&'a str>>>>(HippoRequestAddUrls::VT_URLS, None)
  }
}

pub struct HippoRequestAddUrlsArgs<'a> {
    pub urls: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a , flatbuffers::ForwardsUOffset<&'a  str>>>>,
}
impl<'a> Default for HippoRequestAddUrlsArgs<'a> {
    #[inline]
    fn default() -> Self {
        HippoRequestAddUrlsArgs {
            urls: None,
        }
    }
}
pub struct HippoRequestAddUrlsBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoRequestAddUrlsBuilder<'a, 'b> {
  #[inline]
  pub fn add_urls(&mut self, urls: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoRequestAddUrls::VT_URLS, urls);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoRequestAddUrlsBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoRequestAddUrlsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoRequestAddUrls<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoUrlEntryOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoUrlEntry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoUrlEntry<'a> {
    type Inner = HippoUrlEntry<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoUrlEntry<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoUrlEntry {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args HippoUrlEntryArgs<'args>) -> flatbuffers::WIPOffset<HippoUrlEntry<'bldr>> {
      let mut builder = HippoUrlEntryBuilder::new(_fbb);
      builder.add_length(args.length);
      if let Some(x) = args.title { builder.add_title(x); }
      if let Some(x) = args.path { builder.add_path(x); }
      builder.finish()
    }

    pub const VT_PATH: flatbuffers::VOffsetT = 4;
    pub const VT_TITLE: flatbuffers::VOffsetT = 6;
    pub const VT_LENGTH: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn path(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(HippoUrlEntry::VT_PATH, None)
  }
  #[inline]
  pub fn title(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(HippoUrlEntry::VT_TITLE, None)
  }
  #[inline]
  pub fn length(&self) -> f32 {
    self._tab.get::<f32>(HippoUrlEntry::VT_LENGTH, Some(0.0)).unwrap()
  }
}

pub struct HippoUrlEntryArgs<'a> {
    pub path: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub title: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub length: f32,
}
impl<'a> Default for HippoUrlEntryArgs<'a> {
    #[inline]
    fn default() -> Self {
        HippoUrlEntryArgs {
            path: None,
            title: None,
            length: 0.0,
        }
    }
}
pub struct HippoUrlEntryBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoUrlEntryBuilder<'a, 'b> {
  #[inline]
  pub fn add_path(&mut self, path: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoUrlEntry::VT_PATH, path);
  }
  #[inline]
  pub fn add_title(&mut self, title: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoUrlEntry::VT_TITLE, title);
  }
  #[inline]
  pub fn add_length(&mut self, length: f32) {
    self.fbb_.push_slot::<f32>(HippoUrlEntry::VT_LENGTH, length, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoUrlEntryBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoUrlEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoUrlEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoReplyAddedUrlsOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoReplyAddedUrls<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoReplyAddedUrls<'a> {
    type Inner = HippoReplyAddedUrls<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoReplyAddedUrls<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoReplyAddedUrls {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args HippoReplyAddedUrlsArgs<'args>) -> flatbuffers::WIPOffset<HippoReplyAddedUrls<'bldr>> {
      let mut builder = HippoReplyAddedUrlsBuilder::new(_fbb);
      if let Some(x) = args.urls { builder.add_urls(x); }
      builder.finish()
    }

    pub const VT_URLS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn urls(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<HippoUrlEntry<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<HippoUrlEntry<'a>>>>>(HippoReplyAddedUrls::VT_URLS, None)
  }
}

pub struct HippoReplyAddedUrlsArgs<'a> {
    pub urls: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a , flatbuffers::ForwardsUOffset<HippoUrlEntry<'a >>>>>,
}
impl<'a> Default for HippoReplyAddedUrlsArgs<'a> {
    #[inline]
    fn default() -> Self {
        HippoReplyAddedUrlsArgs {
            urls: None,
        }
    }
}
pub struct HippoReplyAddedUrlsBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoReplyAddedUrlsBuilder<'a, 'b> {
  #[inline]
  pub fn add_urls(&mut self, urls: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<HippoUrlEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoReplyAddedUrls::VT_URLS, urls);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoReplyAddedUrlsBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoReplyAddedUrlsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoReplyAddedUrls<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum HippoMessageOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct HippoMessage<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HippoMessage<'a> {
    type Inner = HippoMessage<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> HippoMessage<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        HippoMessage {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args HippoMessageArgs<'args>) -> flatbuffers::WIPOffset<HippoMessage<'bldr>> {
      let mut builder = HippoMessageBuilder::new(_fbb);
      if let Some(x) = args.user_data { builder.add_user_data(x); }
      if let Some(x) = args.message { builder.add_message(x); }
      builder.add_message_type(args.message_type);
      builder.finish()
    }

    pub const VT_MESSAGE_TYPE: flatbuffers::VOffsetT = 4;
    pub const VT_MESSAGE: flatbuffers::VOffsetT = 6;
    pub const VT_USER_DATA: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn message_type(&self) -> MessageType {
    self._tab.get::<MessageType>(HippoMessage::VT_MESSAGE_TYPE, Some(MessageType::NONE)).unwrap()
  }
  #[inline]
  pub fn message(&self) -> Option<flatbuffers::Table<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(HippoMessage::VT_MESSAGE, None)
  }
  #[inline]
  pub fn user_data(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(HippoMessage::VT_USER_DATA, None)
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_next_song(&self) -> Option<HippoNextSong<'a>> {
    if self.message_type() == MessageType::next_song {
      self.message().map(|u| HippoNextSong::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_prev_song(&self) -> Option<HippoPrevSong<'a>> {
    if self.message_type() == MessageType::prev_song {
      self.message().map(|u| HippoPrevSong::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_play_song(&self) -> Option<HippoPlaySong<'a>> {
    if self.message_type() == MessageType::play_song {
      self.message().map(|u| HippoPlaySong::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_stop_song(&self) -> Option<HippoStopSong<'a>> {
    if self.message_type() == MessageType::stop_song {
      self.message().map(|u| HippoStopSong::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_select_song(&self) -> Option<HippoSelectSong<'a>> {
    if self.message_type() == MessageType::select_song {
      self.message().map(|u| HippoSelectSong::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_request_add_urls(&self) -> Option<HippoRequestAddUrls<'a>> {
    if self.message_type() == MessageType::request_add_urls {
      self.message().map(|u| HippoRequestAddUrls::init_from_table(u))
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn message_as_reply_added_urls(&self) -> Option<HippoReplyAddedUrls<'a>> {
    if self.message_type() == MessageType::reply_added_urls {
      self.message().map(|u| HippoReplyAddedUrls::init_from_table(u))
    } else {
      None
    }
  }

}

pub struct HippoMessageArgs<'a> {
    pub message_type: MessageType,
    pub message: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
    pub user_data: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for HippoMessageArgs<'a> {
    #[inline]
    fn default() -> Self {
        HippoMessageArgs {
            message_type: MessageType::NONE,
            message: None,
            user_data: None,
        }
    }
}
pub struct HippoMessageBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HippoMessageBuilder<'a, 'b> {
  #[inline]
  pub fn add_message_type(&mut self, message_type: MessageType) {
    self.fbb_.push_slot::<MessageType>(HippoMessage::VT_MESSAGE_TYPE, message_type, MessageType::NONE);
  }
  #[inline]
  pub fn add_message(&mut self, message: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoMessage::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_user_data(&mut self, user_data: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HippoMessage::VT_USER_DATA, user_data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HippoMessageBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HippoMessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HippoMessage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_hippo_message<'a>(buf: &'a [u8]) -> HippoMessage<'a> {
  flatbuffers::get_root::<HippoMessage<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_hippo_message<'a>(buf: &'a [u8]) -> HippoMessage<'a> {
  flatbuffers::get_size_prefixed_root::<HippoMessage<'a>>(buf)
}

#[inline]
pub fn finish_hippo_message_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<HippoMessage<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_hippo_message_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<HippoMessage<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
