language: cpp

os: linux

compiler:
- clang
- gcc

env:
- CHECKED=no
- CHECKED=yes

install:
- sudo cpanm File::Slurp Digest::MD5

script:
- make NO_GIT_FILE=1 all run-all-tests
- make NO_GIT_FILE=1 CROSSMINGW=yes all installer windows-zip

addons:
  apt:
    packages:
      - valgrind
      - yasm
      - cpanminus
      - mingw-w64
      - g++-mingw-w64-x86-64
      - mingw-w64-x86-64-dev
      - nsis
      - asciidoc
      - source-highlight

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: REn8sb5HtROhJiCUJKxaY0Gd7vmEK1MqaMxNPGxM4aiUa98vAYXm9u8MaZDo0QV5h+gmgcKNZpTIUHFh6OEdMT62WBMfYNo7+mEbT4ccSbDvDVGL+U3498jglW233lV/8b4lgngeeDPNtSYoydUfcJH2tyiI3xK73Xn82LUCyRlXqJoYc/+9XKQR7miAYJeh/KER1BfHyT4TiwVE63jIWoEUxSmTd2cSRuKSfxY/dleN3fmFNgTbIZFjvKtGmS806FhTA8j8HOgtmm7hluvuOqdLNwZPUf93dlVan3WdiYFT2xxSDMHm0GsIv2oUuJe0tjXEHxs+vjljVD3et8ibTwrK5lH/2am9RSMnV9yNjvcPs8rhG44zV5tFoa+QT+5aRg2fjE6leNbmgyIuSyB/HVCRI6RjpYnyBKYJGwkHpzftR40s+H8o/26ktF3wuxPxDkSnPUqwjnLEgjhMW9zU15PpQZYYLQjdKa+fdpDbJsFmYU7tWprItNB4De18woaEgA3o7M+ss2Ybz2J6Bgk0XII3ngxXIb0frkDkQLX8A7DpR8Kjca5kr4bObzo/IR0Bfyt76ZO8lDco7QFhmgwrhyV4+WPHOWgmpt3aojZ06UkIC/TSrzM3d0Nteo20j/MnwEAs6T26edUworFmjDKe5+l//uirUWcLzh531LizmIs=
  file:
    - build.mingw/Tundra-Binaries.zip
    - build.mingw/Tundra-Setup.exe
  # Important to just pick one build here
  on:
    repo: deplinenoise/tundra
    branch: auto-releases
    condition: $CC = clang && $CHECKED = no
